server:
  port: 8160
spring:
  application:
    name: service-user
  # 环境设置
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.236.91:3306/yygh_user?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: yygh_user
    password: W8Lzm4wBamHXfkC2
  # 返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 110.40.236.91
    port: 6379
    password: gongxiwu666
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500000
    lettuce:
      pool:
        max-wait: -1
  cloud:
    nacos:
      server-addr: 110.40.236.91:8848
# 分页配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true
logging:
  level:
    com.codesniper: debug
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3000


