# 服务端口号
server:
  port: 8082
spring:
  # 服务名
  application:
    name: service-dic-man
  # 环境设置
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.236.91:3306/yygh_dic?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: yygh_dic
    password: ykXAHdPL8ApZdBSJ
  # 返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # redis配置
  redis:
    database: 0
    host: 110.40.236.91
    port: 6379
    password: gongxiwu666
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1
  cloud:
    nacos:
      server-addr: 110.40.236.91:8848
# 分页配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true
logging:
  level:
    com.codesniper: debug
