# 服务端口号
server:
  port: 8081
spring:
# 服务名
  application:
    name: service-hosp
# 环境设置
  profiles:
    active: dev
# 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.236.91:3306/yygh_hosp?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: yygh_hosp
    password: pSjDheEe85AAtTeM
# 返回json全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
# mongodb
    mongodb:
      uri: mongodb://110.40.236.91:27017/yygh_hosp
      auto-index-creation: false
  cloud:
    nacos:
      server-addr: 110.40.236.91:8848
# 分页配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'null'
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true
logging:
  level:
    com.codesniper: debug
